#!/bin/sh

# Same as fluidconv but produces ogg with oggenc (vorbis-tools).

if [ "$1" = "" ]; then
    echo input midi-file missing
    exit 1
fi


for input in $*
do
    # output file name
    output=$input.wav

    fluidsynth -ilv \
	-a file \
	~/sf2/piano/SteinwayGrandPiano1.2.sf2 $input \
	-o audio.file.name=$output

    oggenc -q5 $output
done

exit 0
